// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHKo5pYymzsOz7xzzfGGtnHmXWfFxrUTk',
    appId: '1:922169048076:web:7df06e097517ce83f3c229',
    messagingSenderId: '922169048076',
    projectId: 'prepwise-mvp',
    authDomain: 'prepwise-mvp.firebaseapp.com',
    storageBucket: 'prepwise-mvp.firebasestorage.app',
    measurementId: 'G-WF8N4N4S4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClKd-abGjMtpT8MfxKJb8-epgepr__A5U',
    appId: '1:922169048076:android:7ad0766b5cbf6c6ff3c229',
    messagingSenderId: '922169048076',
    projectId: 'prepwise-mvp',
    storageBucket: 'prepwise-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo-LoJOn5ujMpE76JJ-kYsmprUHGY-WNs',
    appId: '1:922169048076:ios:55a5a5ad014a1b69f3c229',
    messagingSenderId: '922169048076',
    projectId: 'prepwise-mvp',
    storageBucket: 'prepwise-mvp.firebasestorage.app',
    iosClientId: '922169048076-iioun50fnidfilg681s4rvmnphjo7hnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.campus_connect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo-LoJOn5ujMpE76JJ-kYsmprUHGY-WNs',
    appId: '1:922169048076:ios:55a5a5ad014a1b69f3c229',
    messagingSenderId: '922169048076',
    projectId: 'prepwise-mvp',
    storageBucket: 'prepwise-mvp.firebasestorage.app',
    iosClientId: '922169048076-iioun50fnidfilg681s4rvmnphjo7hnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.campus_connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHKo5pYymzsOz7xzzfGGtnHmXWfFxrUTk',
    appId: '1:922169048076:web:7df06e097517ce83f3c229',
    messagingSenderId: '922169048076',
    projectId: 'prepwise-mvp',
    authDomain: 'prepwise-mvp.firebaseapp.com',
    storageBucket: 'prepwise-mvp.firebasestorage.app',
    measurementId: 'G-WF8N4N4S4H',
  );

}